# Form implementation generated from reading ui file 'Educator.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap



        

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        
        # Текст: Выберите тему
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        
        self.verticalLayout.addWidget(self.label)
        
        # Раскрывающийся список тем
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        
        for th in range(9):
            self.comboBox.addItem("")
        
        self.verticalLayout.addWidget(self.comboBox)
        
        # Разделы темы
        self.tabs = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabs.setFont(font)
        self.tabs.setObjectName("tabs")
        
        self.verticalLayout.addWidget(self.tabs)
                
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle("Обучающая система")
        self.label.setText(_translate("MainWindow", "Выберите тему"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Система уравнений с двумя неизвестными"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Показательные уравнения"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Квадратные уравнения"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Линейные уравнения с одной переменной"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Дробно-рациональные уравнения"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Иррациональные уравнения"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Логарифмические уравнения"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Уравнения с модулем"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Биквадратные уравнения"))
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
